### ISSUE TITLE
Feature: Custom ttl attribute name

### ISSUE THREAD

**Issue by gordonbondon** [eredi93/marloss#9]
How about adding an option to change ttl attribute name? Currently its hardcoded to `Expires`

**Comment by eredi93** [comment]
what would this help with? the `Expires` field is only used by DDB for expiring the lock.
can you give me a use case where this would help?
I'd love to avoid adding complexity unless really necessary 😄

**Comment by gordonbondon** [comment]
For example you don't have access to provision new DDBs. Its provided to you and TTL field is not `Expires`. Everything will work, but items will not expire since library will populate wrong field.

**Comment by eredi93** [comment]
@gordonbondon i merged https://github.com/eredi93/marloss/pull/12 i'm going to release a new version later today

**Comment by gordonbondon** [comment]
Thanks!
